### ISSUE TITLE
Add documentation regarding development environment

### ISSUE THREAD

**Issue by LJBD** [synchrotron-solaris/doc-solaris-dev-env#1]
The documentation regarding preparation of a development environment should be added to this repository. It should cover the basics:
- [x] how to install & launch Docker on Windows
- [x] how to build Docker images on Windows
- [x] how to run & use `docker-compose` on Windows
- [x] how to connect it to an IDE.

It can be in Polish and in whatever format you prefer.

**Comment by daneos** [comment]
I think we should, just for completeness sake, have also `docker` and `docker-compose` covered on Linux.

**Comment by LJBD** [comment]
@daneos - totally agreeing with you on that. The thing is, that our interns (who will prepare the initial version of the document) will work on Windows only so we'll have to add it later on our own.

Also, installing & launching Docker on Linux is easy and apart from installation everything else should be platform-agnostic.
