### ISSUE TITLE
Find a way to build & view documentation for Device Classes

### ISSUE THREAD

**Issue by LJBD** [synchrotron-solaris/doc-solaris-dev-env#6]
The Sphinx documentation for Device Classes that you're writing should be built and viewed before they are accepted. There are several things to have in mind:

- [x] The docs should be imported automatically from docstrings in your code. To do so, you'll need [`apidoc`](http://www.sphinx-doc.org/en/stable/man/sphinx-apidoc.html) and [`autodoc`](http://www.sphinx-doc.org/en/stable/ext/autodoc.html) plugins for Sphinx.
- [x] You might also need [`devicedoc`](https://github.com/vxgmichel/pytango-devicedoc) plugin which enables to generate documentation for Tango Device Classes. You have to check that.
- [x] Building the documentation requires project files to be imported. To do so, you have to have all dependencies solved. I'd suggest to build the documentation inside a Docker container.
- [x] You also need to view the generated documentation output outside of the cotainer. I'd suggest using Apache (`httpd`).

**Comment by cpt-majkel** [comment]
According to the second one: [Answer](https://github.com/MaxIV-KitsControls/tango-facadedevice/issues/4)

**Comment by stanislaw47** [comment]
Apache is unnecessary becausue project files are placed in a volume. Thus, they are reachable from both host and container.

**Comment by cpt-majkel** [comment]
To make it clear:
-----------------
1. Prepare your code and add docstrings in appropriate parts of your script
2. Run **one**, chosen device server via PyCharm (as @stanislaw47  said, files are reachable from both host and container)
3. Log in to the tangotest container and in *doc* directory type: 
```console
pip install sphinx
sphinx-quickstart
```
 (remember to choose **YES** in `autodoc` option)
You may need to be root, to do this. If yes type:
```console
docker exec -u 0 -it CONTAINER_NAME bash
```
4. Now go back to PyCharm, open `conf.py` file and add 
```console
import os
import sys
sys.path.insert(0, os.path.abspath('.'))
_this_dir = os.path.dirname(os.path.abspath(__file__))
_setup_dir = os.path.abspath(os.path.join(_this_dir, os.path.pardir, os.path.pardir))
_doc_dir = os.path.join(_setup_dir, 'doc')
sys.path.insert(0, os.path.abspath(_this_dir))
sys.path.insert(0, os.path.abspath(_setup_dir))

from MAIN_FOLDER import PACKAGES, version
```
5. If you document scripts make sure their main routine is protected by  `if __name__ == '__main__'` condition (i.e `run` command)
6. Go to the *doc* directory on the container and type:
```console
sphinx-apidoc -o DOC_SOURCE_DIR/  MAIN_PKG_DIR
sphinx-build -b html source build
```

**Comment by LJBD** [comment]
Great, thanks for the instructions list!
